/** @format */

import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/providers/theme';

const sora = Sora({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});


export const metadata: Metadata = {
	title: 'Proposta Comercial - Tars Projetos',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='pt-BR'
			suppressHydrationWarning>
			<body className={`${sora.className} antialiased`}>
				<ThemeProvider
					attribute={'class'}
					enableSystem
					disableTransitionOnChange>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
